version: '3'
volumes:
  prometheus-data:
    driver: local
  node_modules: {}
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /tmp/prometheus:/tmp/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/tmp/prometheus/prometheus.yml
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.45.0
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
  dev:
    image: docnition/dockwell-dev
    container_name: dockwell-prod-hot
    ports:
      - 3535:3535
    volumes:
      - .:/usr/src
      - node_modules:/usr/src/node_modules
    command: 'npm run dev:hot'
